version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - aws cloudformation package --template-file pdftotxt3.yml --s3-bucket artifactoutbucket --output-template-file lambdaoutput.yaml

artifacts:
  type: zip
  name: pdftotextzip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml
