AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  PDFtoTXTLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: PDFtoTXTLayer
      Description: PDFtoTXTLayer
      Content:
        S3Bucket: artifactoutbucket
        S3Key: pypdf.zip
      CompatibleRuntimes:
        - python3.12
  PdftotxtS3:
    Type: AWS::S3::Bucket
    DependsOn: ExampleInvokePermission
    Properties:
      BucketName: pdfbucket31
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: pdf
            Function: !GetAtt [ pdftotxt, Arn]
  ExampleInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: pdftotxt
    Properties:
      FunctionName:
        Fn::GetAtt:
          - pdftotxt
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::pdfbucket31  
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Description: 'pdf to text lambda'
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::637423317527:role/multirolelamda'
      Environment:
        Variables:
          TARGET_BUCKET: txtbucketstage2
    
      Layers:
        - !Ref PDFtoTXTLayer
