AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  PdftotxtS3:
    Type: AWS::S3::Bucket
    DependsOn: ExampleInvokePermission
    Properties:
      BucketName: mypdftxtbucket123
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: pdf
            Function: !GetAtt [ pdftotxt, Arn]
  ExampleInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: pdftotxt
    Properties:
      FunctionName:
        Fn::GetAtt:
          - pdftotxt
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::mypdftxtbucket123  
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Description: 'test lambda'
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::637423317527:role/multirolelamda'
      Environment:
        Variables:
          TARGET_BUCKET: pdftextstage2bucket
    
      Layers:
        - 'arn:aws:lambda:us-east-1:637423317527:layer:tika:1'
